#!/bin/bash
# Tool for deploying the batchValidator source code. All files will be copied
# to Python site-packages, replacing any modified code. 

# To run this # tool, type './setup' at the command line.

# rm -r /local/python/2.7.12/lib/python2.7/site-packages/variantValidator/
rsync -rv .// /local/python/2.7.12/lib/python2.7/site-packages/VariantValidator/ --delete


# <LICENSE>
# Copyright (C) 2018  Peter Causey-Freeman, University of Leicester
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
# </LICENSE>