[project]
name = "VariantFormatter"
dynamic = ["version"]
description = "Formatting of sequence variants using VariantValidator and HGVS nomenclature"
license = {file = "LICENSE.txt"}
authors = [
    {name = "VariantValidator Contributors", email = "admin@variantvalidator.org"}
]
readme = "README.md"

keywords = [
    "bioinformatics",
    "computational biology",
    "genome variants",
    "genome variation",
    "genomic variants",
    "genomic variation",
    "genomics",
    "hgvs",
    "HGVS",
    "sequence variants",
    "variant formatting"
]

requires-python = ">=3.12"

dependencies = [
    "VariantValidator"
]

classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
    "License :: OSI Approved :: GNU Affero General Public License v3 or later (AGPLv3+)",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Operating System :: OS Independent"
]

[project.urls]
"Homepage" = "https://variantvalidator.org/"
"Documentation" = "https://openvar.github.io/variantValidator/"
"Source" = "https://github.com/openvar/variantValidator"
"Bug Reports" = "https://github.com/openvar/variantValidator/issues"
"Terms of Use" = "https://github.com/openvar/variantValidator#terms-and-conditions-of-use"
"Say Thanks!" = "https://www.buymeacoffee.com/VariantValidatr"

[project.scripts]
variantformatter = "VariantFormatter.bin.variantformatter:main"

[tool.setuptools_scm]
root = "../.."

[tool.setuptools.packages.find]
where = ["../.."]
include = ["VariantFormatter*"]
exclude = ["batch"]

[build-system]
requires = [
    "setuptools>=45",
    "setuptools_scm[toml]>=6.2",
    "wheel"
]
build-backend = "setuptools.build_meta"


# Copyright (C) 2016-2026 VariantValidator Contributors
# This file is part of VariantValidator and is distributed under the
# GNU Affero General Public License, version 3 or (at your option) any
# later version. See the LICENSE file in the project root for the full
# licence terms.
# SPDX-License-Identifier: AGPL-3.0-or-later
